[build]
  command = "npm run build"
  publish = "dist/client"
  functions = "dist/server"

[build.environment]
  NITRO_PRESET = "netlify"
  VITE_SITE_URL = "https://cambodiaspeed.netlify.app"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200
